repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest src/ --verbose
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
      
        name: Run flake8
        entry: flake8 src/ --max-line-length=88 --extend-ignore=E203
        language: system
        types: [python]
        pass_filenames: false